### PR TITLE
Remove @graphql-tools/wrap dependency and replace functionality

### PR DESCRIPTION
**Pull request by jonnydgreen**
Fixes: https://github.com/mercurius-js/auth/issues/74

### CODE REVIEW

**Comment by jonnydgreen** [comment]
Need to run some benchmarking, will update the PR when I've done this!

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by jonnydgreen** [comment]
Apologies for the lateness on this, something came up last week and was unable to work on OS - will aim to run the benchmarks and get this out today/tomorrow! :)

**Comment by jonnydgreen** [comment]
Just ran the benchmarks and no noticeable difference - in-fact, it's ever so slightly quicker

**Pull request merged**
